M48
; DRILL file {KiCad 7.0.8} date Sun 31 Dec 2023 09:55:07 PM IST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-31T21:55:07+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.8484Y-1.2579
X2.8484Y-4.7087
X5.8465Y-1.2579
X5.8465Y-4.7087
T0
M30
